CREATE OR REPLACE TABLE STORI_SILVER_DB_PROD.PROCUREMENT_TO_PAY.TRANSACTIONS (
  PURCHASE_ORDER_ID NUMBER COMMENT 'IDENTIFIER FOR THE ORDER IN OUR FINANCIAL SYSTEM'
  , NETSUITE_ORDER_ID VARCHAR(200) COMMENT 'IDENTIFIER FOR THE ORDER IN NETSUITE SYSTEM'
  , ORDER_LINE_ID NUMBER COMMENT 'IDENTIFIER OF EACH ORDER LINE'
  , AMOUNT FLOAT COMMENT 'AMOUNT RELATED TO THE ORDER LINE'
  , RECEPTION_PERCENT FLOAT COMMENT 'PERCENTAGE OF ORDER LINE RECEIVED'
  , SENT_TO_INVOICE FLOAT COMMENT 'AMOUNT SENT TO BE INVOICED'
  , AMOUNT_INVOICED FLOAT COMMENT 'AMOUNT THAT HAS BEEN INVOICED'
  , AMOUNT_RECOGNIZED FLOAT COMMENT 'AMOUNT THAT HAS BEEN RECOGNIZED'
  , CURRENT_PROVISIONED FLOAT COMMENT 'AMOUNT CURRENTLY PROVISIONED'
  , SENT_TO_REVERSE FLOAT COMMENT 'AMOUNT SENT TO REVERSE A PROVISION'
  , SENT_TO_PROVISION FLOAT COMMENT 'AMOUNT SENT TO BE PROVISIONED'
  , IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT 'INDICATES IF THE RECORD IS ACTIVE'
  , IS_DECEASED BOOLEAN DEFAULT FALSE COMMENT 'INDICATES IF THE PROVISION IS ACTIVE'
  , PROVISION_ID NUMBER (15,0) COMMENT 'IDENTIFICATION OF EACH RECORD OF PROVISION MADE'
  , REVERSION_ID NUMBER (15,0) COMMENT 'IDENTIFICATION OF EACH REVERSION RECORD MADE'
  , LOADED_AT TIMESTAMP_TZ(9) COMMENT 'TIMESTAMP OF WHEN THE RECORD WAS LOADED INTO THE DATABASE'
)
COMMENT = 
    'THIS TABLE STORES INFORMATION ABOUT TRANSACTIONS RELATED TO PURCHASE ORDERS IN THE PROCUREMENT 
    TO PAY PROCESS. IT INCLUDES DETAILS SUCH AS PURCHASE ORDER IDENTIFIERS, NETSUITE ORDER IDs, 
    LINE ITEM AMOUNTS, AND VARIOUS STATES OF PROVISIONING AND INVOICING. FIELDS TRACKING THE STATUS 
    OF PROVISIONS AND REVERSIONS ARE PRESENT, ALONG WITH TIMESTAMPS FOR LOADING. THE TABLE IS 
    DESIGNED TO FACILITATE FINANCIAL REPORTING AND AUDITING PROCESSES, ENSURING TRANSPARENCY IN 
    THE MANAGEMENT OF ORDER LINE FINANCIALS.'
CLUSTER BY (PURCHASE_ORDER_ID, NETSUITE_ORDER_ID, ORDER_LINE_ID)
;