CREATE OR REPLACE SEQUENCE STORI_GOLD_DB_PROD.PROCUREMENT_TO_PAY.SEQUENCE_VENDORBILL_LINE START = 1 INCREMENT = 1 ORDER;

CREATE OR REPLACE TABLE STORI_GOLD_DB_PROD.PROCUREMENT_TO_PAY.VENDORBILL_LINE (
  ID INT NOT NULL DEFAULT STORI_GOLD_DB_PROD.PROCUREMENT_TO_PAY.SEQUENCE_VENDORBILL_LINE UNIQUE PRIMARY KEY
  , BODY_ID INT NOT NULL COMMENT 'BODY ID IDENTIFIER FOR THE LINE'
  , ITEM_ID INT KEY COMMENT 'UNIQUE IDENTIFIER FOR THE ITEM'
  , QUANTITY INT NOT NULL DEFAULT 1 COMMENT 'QUANTITY OF THE ITEM, USUALLY 1'
  , DESCRIPTION VARCHAR(255) NOT NULL COMMENT 'DESCRIPTION OF THE ITEM'
  , RATE DOUBLE NOT NULL COMMENT 'UNIT PRICE OF THE ITEM'
  , DEPARTMENT_ID INT NOT NULL COMMENT 'ID OF THE COST CENTER ASSOCIATED WITH THE ITEM'
  , VERTICAL_ID INT NOT NULL COMMENT 'ID OF THE VERTICAL ASSOCIATED WITH THE ITEM'
  , LOCATION_ID INT NOT NULL COMMENT 'ID OF THE COUNTRY ASSOCIATED WITH THE ITEM'
  , ENTITY_ID INT NOT NULL COMMENT 'ID OF THE ENTITY (THIRD-PARTY) ASSOCIATED WITH THE ITEM, SAME AS THE ENTITY FROM THE HEADER'
  , LOADED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE AND TIME WHEN THE RECORD WAS LOADED INTO THE DATABASE'
)
COMMENT = 
    'THIS TABLE STORES INFORMATION ABOUT PROVISIONED ITEMS, INCLUDING ITEM ID, QUANTITY,
    DESCRIPTION, UNIT PRICE, ASSOCIATED COST CENTERS, VERTICALS, LOCATION AND THIRD-PARTY ENTITY.
    IT TRACKS THE QUANTITY AND UNIT PRICE PER ITEM, ALONG WITH ASSOCIATED DIMENSIONS LIKE DEPARTMENTS AND VERTICALS.'
CLUSTER BY (ENTITY_ID, BODY_ID)
;
