CREATE OR REPLACE TABLE STORI_SILVER_DB_PROD.PROCUREMENT_TO_PAY.LOW_LEVEL_INVOICE_ADJUSTMENTS (
  ID INT PRIMARY KEY COMMENT 'UNIQUE IDENTIFIER FOR EACH ADJUSTMENT RECORD'
  , INVOICE_ID INT COMMENT 'ID OF THE INVOICE BEING ADJUSTED, REFERENCES DOMAIN_INVOICE(ID)'
  , PO_ID INT COMMENT 'ID OF THE PURCHASE ORDER BEING ADJUSTED, OPTIONAL FIELD'
  , SUPPLIER_ID VARCHAR(200) COMMENT 'ID OF THE SUPPLIER ASSOCIATED WITH THE INVOICE'
  , ADJUSTMENT_DATE DATE COMMENT 'DATE WHEN THE ADJUSTMENT WAS MADE'
  , AMOUNT_ADJUSTED FLOAT COMMENT 'AMOUNT ADJUSTED FOR THE INVOICE'
  , CANCELED BOOLEAN COMMENT 'INDICATOR OF WHETHER THE ADJUSTMENT IS CANCELED'
  , COMPLIANT BOOLEAN COMMENT 'INDICATOR OF WHETHER THE ADJUSTMENT IS COMPLIANT'
  , CONFIRMATION VARCHAR(200) COMMENT 'CONFIRMATION STATUS OF THE ADJUSTMENT'
  , ORIGINAL_INVOICE_DATE DATE COMMENT 'ORIGINAL DATE OF THE INVOICE BEFORE ADJUSTMENT'
  , ORIGINAL_INVOICE_NUMBER VARCHAR(500) COMMENT 'ORIGINAL INVOICE NUMBER BEFORE ADJUSTMENT'
  , PAID BOOLEAN COMMENT 'INDICATOR OF WHETHER THE INVOICE IS PAID AFTER ADJUSTMENT'
  , ADJUSTED_TAX_AMOUNT FLOAT COMMENT 'TAX AMOUNT AFTER ADJUSTMENT'
  , ADJUSTED_TOTAL_WITH_TAXES FLOAT COMMENT 'TOTAL AMOUNT WITH TAXES AFTER ADJUSTMENT'
  , CREATED_AT DATE DEFAULT CURRENT_DATE COMMENT 'DATE WHEN THE ADJUSTMENT RECORD WAS CREATED'
  , UPDATED_AT DATE DEFAULT CURRENT_DATE COMMENT 'DATE OF THE LAST UPDATE TO THE ADJUSTMENT RECORD'
  , LOADED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP COMMENT 'TIMESTAMP OF WHEN THE RECORD WAS LOADED INTO THE DATABASE'
)
COMMENT = 'THIS TABLE STORES MANUAL ADJUSTMENTS MADE TO INVOICES OR PURCHASE ORDERS. 
INCLUDES DETAILS SUCH AS INVOICE ID, PO ID, AMOUNTS ADJUSTED, COMPLIANCE STATUS, AND DATES. 
PROVIDES A RECORD OF ANY CHANGES MADE TO FINANCIAL DATA, ALLOWING FOR TRACKING AND AUDITING.'
;